### PR TITLE
48 refactor ci pipeline

### PR DESCRIPTION
**Pull request by victorggonzalez**
This PR contains:
- removed the unused **test** job inside the `cdelivery-*.yml` workflows. We now perform the integration test job in the Graasp Deploy workflow
- `cintegration-ecs-explorer.yml`: include test job that matches the current `cypress.yml ` workflow inside the library repo. 
-  `cintegration-s3-apps.yml`: include test job that matches the current `cypress.yml ` workflow inside apps repos. Add cache to build and deploy jobs to improve speed. 
- `cintegration-s3.yml`: include test job that matches the current `cypress.yml ` workflow inside s3 repos. Add cache to build and deploy jobs to improve speed. 
- adapt all the `*-caller.yml` workflows to improve the changes made

### CODE REVIEW

**Comment by victorggonzalez** [comment]
Added `cintegration-ecs-backend.yml` to include test job that matches the current cypress.yml workflow inside the graasp repo. Add the appropriate secrets to the `cintegration-ecs-backend-caller.yml`

**Comment by victorggonzalez** [comment]
Updated the build job for ecs-backend. Now the ecs-backend workflow has the following jobs:
- build: install yarn dependencies and cache them for the test job, build image and cache it for the test job. Removed the `build docker` from this step and moved it to the **deploy** job. This is because **build** and **test** jobs will be executed every time we push a commit, so we avoid pushing images to ECR every time. 
- test: cache yarn dependencies and build image, and run `yarn test`
- deploy: tag the image, build the docker image, push to the registry, fill task definition and deploy to dev.

**Comment by victorggonzalez** [comment]
Updated the build job for ecs-explorer. Now the ecs-explorer workflow has the following jobs:

- build: install yarn dependencies and cache them for the test job, build image and cache it for the test job. Removed the build docker from this step and moved it to the deploy job. This is because build and test jobs will be executed every time we push a commit, so we avoid pushing images to ECR every time.
- test: cache yarn dependencies and build image, and run cypress test
- deploy: tag the image, build the docker image, push to the registry, fill task definition and deploy to dev.

**Review by juancarlosfarah — CHANGES_REQUESTED** [review]
Nice! Just some minor changes. Also, check to see if you can factor out the `TASK DEFINITION` and the `NUMBER OF TASKS` in a JSON for the ECS workflow.

**Comment by juancarlosfarah** [comment]
@victorggonzalez @pyphilia, is this ready to merge?

**Comment by pyphilia** [comment]
I think this PR is too far behind the main branch to be applied. We should report the changes to a new branch.

I've already applied cache to workflows with a composite so this part is already done.

**Pull request closed without merging**
